# Generated by Django 3.1 on 2020-12-29 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favourited_by',
            field=models.ManyToManyField(related_name='favourited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='auth.user'),
            preserve_default=False,
        ),
    ]
