# Generated by Django 3.1 on 2021-01-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_item_listed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('GR', 'Grocery'), ('ST', 'Stationery'), ('BK', 'Book'), ('ET', 'Electronics'), ('DA', 'Digital Accessories'), ('SP', 'Spare Parts'), ('TG', 'Toys & Games'), ('AT', 'Automotives'), ('TL', 'Tools')], default='GR', max_length=2),
        ),
    ]
