# Generated by Django 3.1 on 2021-01-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='favourited_by',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='market.Profile'),
        ),
    ]
