# Generated by Django 3.1 on 2021-01-02 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0010_auto_20210102_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='favourited_by',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
