# Generated by Django 3.1 on 2021-01-02 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_barter'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='complete_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 2, 15, 26, 25, 212712, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
