# Generated by Django 3.1 on 2021-01-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_barter_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='complete_date',
            field=models.DateField(null=True),
        ),
    ]
