# Generated by Django 3.1 on 2021-01-02 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20210102_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='offer',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='market.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barter',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='market.item'),
        ),
    ]
