# Generated by Django 3.1 on 2021-01-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20210103_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile-default.photo.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
